### PR TITLE
add a Dockerfile

### PR DESCRIPTION
**Pull request by d3287t328**
Chatgpt-4 created all of this.

### CODE REVIEW

**Comment by knrd1** [comment]
Thank you for your work, I appreciate! I will review and get back to you.

**Comment by raoel** [comment]
Some remarks (I did not make the PR and am not owner of this repo)

- Why would you open a port? that's only necessary for traffic TO the bot, not FROM the bot
- use `CMD [ "/usr/local/bin/python3", "-u", "chatgpt.py" ]` as the last line, without the "-u" it will buffer all logs to output until it finishes, which basically means you will not get logs until you kill the container, which is very inconvenient.

(my Dockerfile is almost exactly the same, except no open port - and works fine)

Good call to add a requirements.txt!

**Review by knrd1 — COMMENTED** [review]
- lines 13 and 14 not required, bot doesn't listen on port 80
- line 17 - add unbuffered mode:
CMD ["python", "-u", "./chatgpt.py"]

**Review by knrd1 — APPROVED** [review]

**Review by knrd1 — COMMENTED** [review]
To build the Docker image, you can use the following command:
```docker build -t my-chatgpt-app .```

To run the Docker container, you can use the following command:
```docker run -it my-chatgpt-app```

To detach from a running Docker, press Ctrl + P. While holding down Ctrl, press Q.

To reattach to the container later, you can use the following command:
```docker attach container_id```

**Pull request merged**
